# Generated by Django 4.1.3 on 2024-05-10 03:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('airportoffice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airports',
            name='iname',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
