# Generated by Django 4.1.3 on 2024-05-10 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airportoffice', '0002_airports_iname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airports',
            old_name='iname',
            new_name='arrivaltime',
        ),
    ]
