# Generated by Django 4.1.3 on 2024-05-10 03:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('airportoffice', '0003_rename_iname_airports_arrivaltime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airports',
            old_name='aname',
            new_name='airportname',
        ),
        migrations.AddField(
            model_name='airports',
            name='departtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airports',
            name='destinyname',
            field=models.CharField(default='kochin', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airports',
            name='arrivaltime',
            field=models.DateTimeField(),
        ),
    ]
